import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import { makeExample, serializeProject } from '../../src/project.mjs';
import { verifyWifBytes } from '../../src/wif-readback.mjs';
const dir=process.env.BROWSER_ARTIFACT_DIR??'tests/browser/artifacts',base=process.env.BASE_URL??'http://127.0.0.1:4173';
await mkdir(dir,{recursive:true});const results=[],errors=[],requests=[];let browser;
try{browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});}catch(error){await writeFile(`${dir}/results.json`,JSON.stringify({status:'blocked',stage:'browser-launch',testsRun:0,sandbox:true,error:error.message},null,2));throw error;}
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
async function scenario(name,fn){try{await fn();results.push({name,status:'passed'});}catch(error){results.push({name,status:'failed',error:error.message,visibleStatus:await page.locator('#status').textContent().catch(()=>null)});await page.screenshot({path:`${dir}/failure.png`,fullPage:true}).catch(()=>{});throw error;}}
const compile=async()=>{await page.locator('#compile').click();await page.locator('#result').waitFor({state:'visible'});};
const load=async project=>{await page.locator('.import').evaluate(el=>el.open=true);await page.locator('#project-json').fill(serializeProject(project));await page.locator('#load-json').click();};
const download=async id=>{const waiting=page.waitForEvent('download');await page.locator(id).click();const d=await waiting;const stream=await d.createReadStream();const chunks=[];for await(const c of stream)chunks.push(c);return{name:d.suggestedFilename(),text:Buffer.concat(chunks).toString('utf8')};};
try{
 await scenario('Japanese and English UI; keyboard skip link and roving motif editing',async()=>{
  await page.goto(base);assert.equal(await page.locator('html').getAttribute('lang'),'ja');await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(e=>e===document.activeElement),true);await page.locator('#language').selectOption('en');assert.equal(await page.locator('h1').textContent(),'From motif to mechanism.');await page.locator('#motif-grid button[tabindex="0"]').focus();await page.keyboard.press('ArrowRight');const b=page.locator('#motif-grid button[data-row="0"][data-col="1"]');assert.equal(await b.evaluate(e=>e===document.activeElement),true);const value=await b.getAttribute('aria-pressed');await page.keyboard.press('Space');assert.notEqual(await b.getAttribute('aria-pressed'),value);await page.locator('#undo').click();assert.equal(await b.getAttribute('aria-pressed'),value);
 });
 await scenario('Twill proof, every-cell match, WIF readback and downloads',async()=>{
  await page.locator('#example-twill').click();await compile();assert.equal(await page.locator('#result-summary strong').textContent(),'4');assert.equal(await page.locator('.group').count(),4);assert.equal(await page.locator('#witnesses p').count(),6);const wif=await download('#download-wif');assert.equal(verifyWifBytes(wif.text,makeExample().motif).checkedCells,64);assert.ok((await download('#download-svg')).text.includes('3 × 3 REPEAT'));assert.ok((await download('#download-threading')).text.includes('PICK -> RAISED SHAFTS'));const report=JSON.parse((await download('#download-report')).text);assert.equal(report.requiredShafts,4);assert.equal(report.checkedCells,64);await page.screenshot({path:`${dir}/desktop.png`,fullPage:true});await page.locator('#language').selectOption('ja');await page.screenshot({path:`${dir}/desktop-ja.png`,fullPage:true});await page.locator('#language').selectOption('en');
 });
 await scenario('Cap failure preserves motif and disables draft export',async()=>{
  const before=await page.locator('#motif-grid button').evaluateAll(xs=>xs.map(x=>x.getAttribute('aria-pressed')));await page.locator('#shaft-cap').fill('3');assert.equal(await page.locator('#download-wif').isDisabled(),true);await compile();assert.ok(await page.locator('#cap-failure').isVisible());assert.ok((await page.locator('#cap-failure').textContent()).includes('needs 4 shafts'));assert.equal(await page.locator('#download-wif').isDisabled(),true);assert.deepEqual(await page.locator('#motif-grid button').evaluateAll(xs=>xs.map(x=>x.getAttribute('aria-pressed'))),before);const saved=JSON.parse((await download('#save-project')).text);assert.equal(saved.shaftCap,3);assert.deepEqual(saved.motif,makeExample().motif);
 });
 await scenario('Wraparound and unbounded floats warn about non-interlacing',async()=>{
  await page.locator('#example-boundary').click();await compile();assert.ok((await page.locator('#degenerate').textContent()).includes('never interlace'));const lines=await page.locator('.float-row').allTextContents();assert.ok(lines.some(s=>s.includes('Weft · back')&&s.includes('2')&&s.includes('3')));assert.ok(lines.some(s=>s.includes('Unbounded')));assert.ok(await page.locator('#repeat-preview svg').isVisible());
 });
 await scenario('Safe JSON errors, injection rejection, successful save/reload',async()=>{
  await page.locator('.import').evaluate(el=>el.open=true);await page.locator('#project-json').fill('{"bad":true}');await page.locator('#load-json').click();assert.equal(await page.locator('#status').getAttribute('class'),'error');assert.equal(await page.locator('#download-wif').isDisabled(),true);const p=makeExample('plain');p.title='<script>alert(1)</script> & 試作';await load(p);await compile();assert.equal(await page.locator('script:not([src])').count(),0);assert.deepEqual(JSON.parse((await download('#save-project')).text),p);const injected={...p,title:'bad\r\n[LIFTPLAN]\r\n1=0'};await page.locator('#project-json').fill(JSON.stringify(injected));await page.locator('#load-json').click();assert.ok((await page.locator('#status').textContent()).includes('Title'));assert.equal(await page.locator('#title').inputValue(),p.title);
 });
 await scenario('Oversized file and stale file reads never replace newer edits',async()=>{
  await page.locator('#open-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(65537,32)});assert.ok((await page.locator('#status').textContent()).includes('64 KiB'));
  await page.evaluate(()=>{const original=File.prototype.text;File.prototype.text=async function(){await new Promise(r=>setTimeout(r,350));return original.call(this);};});
  await page.locator('#open-file').setInputFiles({name:'twill.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(makeExample()))});await page.locator('#example-plain').click();await page.waitForTimeout(550);assert.equal(await page.locator('#width').inputValue(),'4');assert.equal(await page.locator('#title').inputValue(),'Plain weave');
 });
 await scenario('Download creation errors remain visible',async()=>{await page.evaluate(()=>{window.savedCreateObjectURL=URL.createObjectURL;URL.createObjectURL=()=>{throw Error('test failure')};});await page.locator('#save-project').click();assert.ok((await page.locator('#status').textContent()).includes('could not be created'));await page.evaluate(()=>{URL.createObjectURL=window.savedCreateObjectURL;delete window.savedCreateObjectURL;});});
 await scenario('Resize validates bounds; undo restores cropped cells',async()=>{
  await page.locator('#width').fill('33');await page.locator('#resize').click();assert.ok((await page.locator('#status').textContent()).includes('1 to 32'));assert.equal(await page.locator('#motif-grid button').count(),16);await page.locator('#width').fill('2');await page.locator('#height').fill('2');await page.locator('#resize').click();assert.equal(await page.locator('#motif-grid button').count(),4);await page.locator('#undo').click();assert.equal(await page.locator('#motif-grid button').count(),16);
 });
 await scenario('Cancellation and edits invalidate a delayed compile',async()=>{
  await page.route('**/worker.mjs',async route=>{await new Promise(r=>setTimeout(r,500));await route.continue();});await page.locator('#compile').click();await page.locator('#cancel').click();await page.waitForTimeout(650);assert.equal(await page.locator('#result').isHidden(),true);assert.equal(await page.locator('#download-wif').isDisabled(),true);assert.ok((await page.locator('#status').textContent()).includes('Cancelled'));
  await page.locator('#compile').click();await page.locator('#example-twill').click();await page.waitForTimeout(650);assert.equal(await page.locator('#result').isHidden(),true);await page.unroute('**/worker.mjs');await compile();assert.equal(await page.locator('#result-summary strong').textContent(),'4');
 });
 await scenario('Mobile layout, 32×32 internal scrolling and no page overflow',async()=>{
  await page.setViewportSize({width:390,height:844});await page.locator('#language').selectOption('ja');await page.locator('#width').fill('32');await page.locator('#height').fill('32');await page.locator('#resize').click();await page.locator('#shaft-cap').fill('32');await compile();assert.equal(await page.locator('#motif-grid button').count(),1024);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await page.locator('.grid-scroll').evaluate(el=>el.scrollWidth>el.clientWidth));await page.screenshot({path:`${dir}/mobile-max.png`,fullPage:true});await page.locator('#example-twill').click();await compile();await page.screenshot({path:`${dir}/mobile.png`,fullPage:true});
 });
 await scenario('No external runtime requests or browser exceptions',async()=>{assert.deepEqual(errors,[]);assert.ok(requests.every(url=>url.startsWith(base)||url.startsWith('blob:')),JSON.stringify(requests));});
 const budgetPage=await context.newPage();
 await scenario('An unresponsive worker is stopped at the budget',async()=>{await budgetPage.addInitScript(()=>{window.Worker=class{postMessage(){}terminate(){}};});await budgetPage.goto(base);await budgetPage.locator('#language').selectOption('en');await budgetPage.locator('#compile').click();await budgetPage.locator('#status').filter({hasText:'5-second budget'}).waitFor({timeout:7000});assert.equal(await budgetPage.locator('#compile').isDisabled(),false);assert.equal(await budgetPage.locator('#cancel').isHidden(),true);assert.equal(await budgetPage.locator('#download-wif').isDisabled(),true);});await budgetPage.close();
}finally{await writeFile(`${dir}/results.json`,JSON.stringify({status:results.some(r=>r.status==='failed')?'failed':'passed',sandbox:true,results,errors,requests},null,2));await browser.close();}
